## -----------------------------------------------------------##
## ░██████╗██╗░░██╗██╗░░░██╗██╗░░░░░░█████╗░███╗░░██╗██████╗░ ##
## ██╔════╝██║░██╔╝╚██╗░██╔╝██║░░░░░██╔══██╗████╗░██║██╔══██╗ ##
## ╚█████╗░█████═╝░░╚████╔╝░██║░░░░░███████║██╔██╗██║██║░░██║ ##
## ░╚═══██╗██╔═██╗░░░╚██╔╝░░██║░░░░░██╔══██║██║╚████║██║░░██║ ##
## ██████╔╝██║░╚██╗░░░██║░░░███████╗██║░░██║██║░╚███║██████╔╝ ##
## ╚═════╝░╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░ ##
## -----------------------------------------------------------##
##                       Author: MrErrors                     ##
##                        Version: 1.0.1                      ##
## -----------------------------------------------------------##
# Should the Missions be enabled or not?
enabled: true

# Choose what missions categories should be enabled or not.
Missions-Categories:
  Farming: True

# The title and the amount of rows for this menu.
title: "&8SkyLand Island Missions"
rows: 6

# All items related to the island panel menu
# NOTE: you can find more options for values found
# on the wiki found here ➔ WIKI MENU ITEMS LINK!
items:
    '1':
        name: "&fKilling Missions"
        slot: 19
        material: diamond_sword
        action:
            open-menu: Crafting-Missions
        lore:
        - Test
    '2':
        name: "&fCrafting Missions"
        slot: 20
        material: crafting_table
        action:
            open-menu: Crafting-Missions
        lore:
        - ''
    '3':
        name: "&fBlock Missions"
        slot: 21
        material: diamond_pickaxe
        action:
            open-menu: Block-Missions
        lore:
        - ''
    '4':
        name: "&fIsland Missions"
        slot: 22
        material: player_head
        skull: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDUyOGVkNDU4MDI0MDBmNDY1YjVjNGUzYTZiN2E5ZjJiNmE1YjNkNDc4YjZmZDg0OTI1Y2M1ZDk4ODM5MWM3ZCJ9fX0=
        action:
            open-menu: Island-Missions
        lore:
        - ''
    '5':
        name: "&fFishing Missions"
        slot: 23
        material: fishing_rod
        action:
            open-menu: Fishing-Missions
        lore:
        - ''
    '6':
        name: "&fEnchanting Missions"
        slot: 24
        material: enchanting_table
        action:
            open-menu: Enchanting-Missions
        lore:
        - ''
    '7':
        name: "&fFarming Missions"
        slot: 25
        material: diamond_hoe
        action:
            open-menu: Farming-Missions
        lore:
        - ''
    '8':
        name: "&fItem Missions"
        slot: 31
        material: nether_star
        action:
            open-menu: Item-Missions
        lore:
        - ''
    '9':
        name: "&fBack to Panel"
        slot: 49
        material: tipped_arrow
        effects:
            type: minecraft:healing
        action:
            open-menu: Island-Panel
        lore:
        - ''

# Filler is the menu border of non-clickable items for layouts
filler:
    enabled: true
    items:
        '1':
            material: black_stained_glass_pane
            fill: false
            slots:
            - 0
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7
            - 8
            - 45
            - 46
            - 47
            - 48
            - 49
            - 50
            - 51
            - 52
            - 53
